function DatasetExplorer({ rows = [] }) {
  const columns = [
    "customerID",
    "gender",
    "SeniorCitizen",
    "tenure",
    "Contract",
    "PaymentMethod",
    "MonthlyCharges",
    "Churn",
  ];

  if (!rows || rows.length === 0) {
    return null;
  }

  return (
    <section className="mb-8 rounded-3xl bg-white p-8 shadow-lg">
      <p className="text-sm font-semibold uppercase tracking-widest text-blue-600">
        Dataset Explorer
      </p>

      <h2 className="mt-2 text-3xl font-bold text-slate-900">
        Source Customer Records
      </h2>

      <p className="mt-3 text-slate-500">
        Preview of cleaned customer data generated by the Python analytics pipeline.
      </p>

      <div className="mt-8 overflow-hidden rounded-2xl border border-slate-200">
        <div className="overflow-x-auto">
          <table className="min-w-full text-left">
            <thead className="bg-slate-100">
              <tr>
                {columns.map((column) => (
                  <th
                    key={column}
                    className="whitespace-nowrap px-5 py-4 text-sm font-bold text-slate-700"
                  >
                    {column}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {rows.slice(0, 10).map((row, index) => (
                <tr
                  key={row.customerID || index}
                  className="border-t border-slate-200 hover:bg-blue-50"
                >
                  {columns.map((column) => (
                    <td
                      key={column}
                      className="whitespace-nowrap px-5 py-4 text-sm text-slate-600"
                    >
                      {String(row[column] ?? "-")}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

export default DatasetExplorer;